Chet 189 ssm rds restore (#95)
* CHET-188: Retrieve secrets from AWS secrets manager

* CHET-188: Retrieve secrets from AWS secrets manager and create a separate policy to allow for secretsmanager access

* CHET-188: extract secret string from secretsstore

* CHET-188: sync db dump directory from S3 into downloads

* CHET-188: Remove 'at' usage to schedule/run a job. Execute the command directly

* CHET-188: Query RDS instance with credentials and establish connection from SSM playbook

* CHET-188: Add restore command to assert playbook to restore database

* CHET-188: Fix bad substitution in playbook

* CHET-188: Fix missing substitution

* CHET-188: Remove duplication in security group custom resource code. Change S3 bucket policy to retain on delete

* CHET-188: Make IAM policy for secret key dynamic

* CHET-188: Make IAM policy for secret key dynamic - use stackname instead of id

* CHET-188: Create a document to report on Restore SSM command status

* CHET-188: Filter empty security group IDs

* CHET-188: Use set instead of list for to ensure we don't add/remove the same security group

* CHET-188: Add missing sg rule

* CHET-188: Add json output to command

* CHET-189: Fix python formatiing

* CHET-189: PR feedback - remove number of jobs param from pg_restore and add a 12 hour timeout to db restore ssm command

diff --git a/templates/migration-stack/migration-helper.yml b/templates/migration-stack/migration-helper.yml
--- a/templates/migration-stack/migration-helper.yml
+++ b/templates/migration-stack/migration-helper.yml
@@ -14,6 +14,17 @@ Parameters:
   RDSSecurityGroup:
     Description: "The Security Group attached to RDS, access to PostgreSQL port will be open from Migration Helper Security Group"
     Type: String
+  RDSEndpoint:
+    Description: "The RDS endpoint address that hosts the database on AWS"
+    Type: String
+  RDSPort:
+    Description: "The port on the RDS Server to connect to to restore the database backup"
+    Type: String
+    Default: "5432"
+  RDSDbName:
+    Description: "The name of the database  on the RDS Server"
+    Type: String
+    Default: "jira"
   HelperInstanceType:
     Description: "The Instance Type of Helper EC2 Instance"
     Type: String
@@ -31,7 +42,8 @@ Parameters:
 Resources:
 
   #S3 Bucket for Database Transfer
-  #TODO: Stack deletion fails when the bucket is non-empty. Fix this - https://stackoverflow.com/questions/40383470/can-i-force-cloudformation-to-delete-non-empty-s3-bucket
+  #Stack deletion fails when the bucket is non-empty. To fix this, we need a lambda that cleans the bucket - https://stackoverflow.com/questions/40383470/can-i-force-cloudformation-to-delete-non-empty-s3-bucket
+  # Until then, set the Deletion policy to retain
   MigrationBucket:
     Type: AWS::S3::Bucket
     Properties:
@@ -45,7 +57,8 @@ Resources:
           - AbortIncompleteMultipartUpload:
               DaysAfterInitiation: 4
             Status: "Enabled"
-    DeletionPolicy: Delete
+    DeletionPolicy: Retain
+    UpdateReplacePolicy: Retain
 
   #EC2 Migration Helper
   HelperLaunchConfig:
@@ -130,14 +143,25 @@ Resources:
                 content: !Sub
                   - |
                     #!/bin/bash
-                    echo "this script will pull the secret from secrets manager"
-                    echo "A RDS endpoint needs to be passed into the template"
                     DATABASE_DOWNLOAD_DIR="/efs/downloads/db.dump"
                     mkdir -p $DATABASE_DOWNLOAD_DIR
-                    aws secretsmanager  get-secret-value --secret-id ${SecretIdentifier} --region ${AWS::Region} --output text --query "SecretString"
-                    aws s3 sync s3://${MigrationBucket}/db.dump/ $DATABASE_DOWNLOAD_DIR --region ${AWS::Region}
-                    echo "${RDSEndPoint}"
-                  - { RDSEndPoint: "rds-dns-address", SecretIdentifier: "atl-qs-rds-password", MigrationBucket: !Ref MigrationBucket }
+                    DB_DUMP_LOG_FILE="/var/atlassian/dc-migration-assistant/pg_dump-log.txt"
+                    SECRET_PASSWORD=`aws secretsmanager  get-secret-value --secret-id ${SecretIdentifier} --region ${AWS::Region} --output text --query "SecretString"`
+                    aws s3 sync s3://${MigrationBucket}/db.dump/ $DATABASE_DOWNLOAD_DIR --region ${AWS::Region} | tee $DB_DUMP_LOG_FILE
+                    echo "Restoring database from $DATABASE_DOWNLOAD_DIR to ${DBHost}:${DBPort}/$DBName" | tee $DB_DUMP_LOG_FILE
+                    PGPASSWORD=$SECRET_PASSWORD pg_restore -h ${DBHost} -U ${DBUser} -d ${DBName} -p ${DBPort} -F d --verbose $DATABASE_DOWNLOAD_DIR 2>&1 | tee $DB_DUMP_LOG_FILE
+                    PG_RESTORE_EXIT_CODE=$?
+                    ERRORS_EXIST=`grep -qiE 'error|warning' /var/atlassian/dc-migration-assistant/pg_dump-log.txt && echo 'true' || echo 'false'`
+                    RESTORE_COMPLETE=`grep -qiE 'pg_restore: finished main parallel loop' /var/atlassian/dc-migration-assistant/pg_dump-log.txt && echo 'true' || echo 'false'`
+                    echo -e "{\"is_restore_complete\":\""$RESTORE_COMPLETE"\",\"is_error_present\":\""$ERRORS_EXIST"\", "return_code":\""$PG_RESTORE_EXIT_CODE"\"}"
+                  - {
+                    SecretIdentifier: !Sub "atl-${AWS::StackName}-app-rds-password",
+                    MigrationBucket: !Ref MigrationBucket,
+                    DBHost: !Ref RDSEndpoint,
+                    DBPort: !Ref RDSPort,
+                    DBName: !Ref RDSDbName,
+                    DBUser: "atljira"
+                  }
                 mode: "000755"
           prepare_efs_sync_script:
             packages:
@@ -339,8 +363,7 @@ Resources:
               - Action:
                   - 'secretsmanager:GetSecretValue'
                 Effect: Allow
-                Resource: !Sub ['arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretIdentifier}-??????', { SecretIdentifier: "atl-qs-rds-password"
-                }]
+                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:atl-${AWS::StackName}-app-rds-password-??????"
 
       # TODO: Reduce this to minimum required perms
       #   - PolicyName: Administrator
@@ -384,56 +407,40 @@ Resources:
           ec2client = boto3.client('ec2')
           def lambda_handler(event, context):
             try:
-                  efssg =  event['ResourceProperties']['EFSSG']
-                  rdssg =  event['ResourceProperties']['RDSSG']
-                  evsg = event['ResourceProperties']['HelperSG']
-                  if event['RequestType'] == 'Delete':
-                      response = ec2client.revoke_security_group_ingress(
-                          GroupId=efssg,
-                          IpPermissions=[
-                              {'IpProtocol': 'tcp',
-                              'FromPort': 2049,
-                              'ToPort': 2049,
-                              'UserIdGroupPairs': [{'GroupId': evsg}]}
-                          ]
-                      )
-                      print(response)
-                      response = ec2client.revoke_security_group_ingress(
-                          GroupId=rdssg,
-                          IpPermissions=[
-                              {'IpProtocol': 'tcp',
-                              'FromPort': 5432,
-                              'ToPort': 5432,
-                              'UserIdGroupPairs': [{'GroupId': evsg}]}
-                          ]
-                      )
-                      print(response)
-                      responseData = {'Delete': 'SUCCESS'}
-                      cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
-                  if event['RequestType'] == 'Create':
-                      response = ec2client.authorize_security_group_ingress(
-                          GroupId=efssg,
-                          IpPermissions=[
-                              {'IpProtocol': 'tcp',
-                              'FromPort': 2049,
-                              'ToPort': 2049,
-                              'UserIdGroupPairs': [{'GroupId': evsg}]}
-                          ]
-                      )
-                      response = ec2client.authorize_security_group_ingress(
-                          GroupId=rdssg,
-                          IpPermissions=[
-                              {'IpProtocol': 'tcp',
-                              'FromPort': 5432,
-                              'ToPort': 5432,
-                              'UserIdGroupPairs': [{'GroupId': evsg}]}
-                          ]
-                      )
-                      responseData = {'Create': 'SUCCESS'}
-                      cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
-                  if event['RequestType'] == 'Update':
-                      responseData = {'Update': 'SUCCESS'}
-                      cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
+              efssg =  {'sg': event['ResourceProperties']['EFSSG'], 'from': 2049, 'to': 2049 }
+              rdssg =  {'sg': event['ResourceProperties']['RDSSG'], 'from': 5432, 'to': 5432 }
+              helper_sg = event['ResourceProperties']['HelperSG']
+              if event['RequestType'] == 'Delete':
+                for security_group_props in [efssg, rdssg]:
+                  response = ec2client.revoke_security_group_ingress(
+                      GroupId=security_group_props['sg'],
+                      IpPermissions=[
+                          {'IpProtocol': 'tcp',
+                          'FromPort': security_group_props['from'],
+                          'ToPort': security_group_props['to'],
+                          'UserIdGroupPairs': [{'GroupId': helper_sg}]}
+                      ]
+                  )
+                  print(response)
+                responseData = {'Delete': 'SUCCESS'}
+                cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
+              if event['RequestType'] == 'Create':
+                for security_group_props in [efssg, rdssg]:
+                  response = ec2client.authorize_security_group_ingress(
+                      GroupId=security_group_props['sg'],
+                      IpPermissions=[
+                          {'IpProtocol': 'tcp',
+                          'FromPort': security_group_props['from'],
+                          'ToPort': security_group_props['to'],
+                          'UserIdGroupPairs': [{'GroupId': helper_sg}]}
+                      ]
+                  )
+                  print(response)
+                responseData = {'Create': 'SUCCESS'}
+                cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
+              if event['RequestType'] == 'Update':
+                responseData = {'Update': 'SUCCESS'}
+                cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
             except Exception as e:
                 responseData = {'Error': str(e)}
                 cfnresponse.send(event, context, cfnresponse.FAILED, responseData)
@@ -493,7 +500,7 @@ Resources:
             runCommand:
             - "#!/bin/bash"
             - runuser -l jira -c '/opt/atlassian/dc-migration-assistant/restore-db-to-rds.sh'
-            timeoutSeconds: "60" #TODO: What is the correct value for timeout seconds here?
+            timeoutSeconds: "43200" #12 hours
             workingDirectory: "/opt/atlassian/dc-migration-assistant/"
       DocumentType: "Command"
 
